# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subheading',
            field=models.CharField(default='example subheading', max_length=50),
            preserve_default=False,
        ),
    ]
