# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 09:58
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpost_subheading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
