# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20170315_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='subheading',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
