# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:27
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20170315_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('section_heading', wagtail.wagtailcore.blocks.CharBlock()), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('json', 'JSON'), ('bash', 'BASH')])), ('code', wagtail.wagtailcore.blocks.TextBlock())))), ('html', wagtail.wagtailcore.blocks.RawHTMLBlock()))),
        ),
    ]
